### ISSUE TITLE
PVS1 levels regarding

### ISSUE THREAD

**Issue by imran-igib** [JiguangPeng/autopvs1#13]
Hi, 
I just want to know what is that L0,L1,L2E annotation in PVS1.level files? Could you kindly elaborate the criteria used?

**Comment by wuzhaoqi1015** [comment]
Criteria for LoF disease mechanism:
    1) Follow PVS1 Flowchart if 'L0'
    2) Decrease final strength by one level (i.e. VeryStrong to Strong) if 'L1'
    3) Decrease final strength by two levels (i.e. VeryStrong to Moderate) if 'L2'
    4) If there is no evidence that LOF variants cause disease, PVS1 should not
       be applied at any strength level.

**Comment by wuzhaoqi1015** [comment]
> Hi, I just want to know what is that L0,L1,L2E annotation in PVS1.level files? Could you kindly elaborate the criteria used?

Criteria for LoF disease mechanism
        1) Follow PVS1 Flowchart if 'L0'
        2) Decrease final strength by one level (i.e. VeryStrong to Strong) if 'L1'
        3) Decrease final strength by two levels (i.e. VeryStrong to Moderate) if 'L2'
        4) If there is no evidence that LOF variants cause disease, PVS1 should not
           be applied at any strength level.

**Comment by josephhalstead** [comment]
What is the difference between L3E and L3?

Many Thanks,

Joseph
