### ISSUE TITLE
missing “--fasta”

### ISSUE THREAD

**Issue by zhuying412** [JiguangPeng/autopvs1#14]
the vep command miss paramter "--fasta"?
it's required by "--hgvs".

**Comment by asortiz** [comment]
Hello!

Sorry for re-opening this thread but I have the same problem (see below). How did you resolve? Thanks in advance.

ERROR:
`MSG: ERROR: Cannot generate HGVS coordinates (--hgvs) in offline mode without a FASTA file (see --fasta)`

Adrián

**Comment by jammywwh** [comment]
Hi, @asortiz 
I hava the same problem, may be you can try to:
1. add the following code to the read_data.py 
fasta_hg19 = config['HG19']['genome']
fasta_hg38 = config['HG38']['genome']
2. add the following code to the autoPVS1.py 
line16: from .read_data import transcripts_hg19, transcripts_hg38, genome_hg19, genome_hg38, fasta_hg19, fasta_hg38
line43-44: self.fasta = fasta_hg19
line46-47: self.fasta = fasta_hg38
2 vepcommand add: --fasta ''' + self.fasta + ''' \

It works after modified.
Hope that helps.

Jammy
