### ISSUE TITLE
Potential bug in AutoPVS1 for CNV input data

### ISSUE THREAD

**Issue by lourdesrosano** [JiguangPeng/autopvs1#15]
Hello @JiguangPeng,

From AutoPVS1's description and FAQ, it seems that the tool should be applicable to copy number variants (CNVs) as well. This is indeed the case when we use example CNV queries in the online version of the tool, e.g. see results for [11-2797090-2869333-DEL](http://autopvs1.genetics.bgi.com/cnv/hg38/11-2797090-2869333-DEL) or [1-215844214-215849058-DUP](http://autopvs1.genetics.bgi.com/cnv/hg38/1-215844214-215849058-DUP).

However, when we attempt to use the exact same CNV queries with the latest Python version of the tool, this does not seem to work, and a `TypeError` is thrown by the package:

```
>>> from autopvs1 import AutoPVS1
>>> demo=AutoPVS1('11-2797090-2869333-DEL', 'hg38')
TypeError: Wrong VCF Record
>>> demo=AutoPVS1('1-215844214-215849058-DUP', 'hg38')
TypeError: Wrong VCF Record
```

It seems that this could be triggered by a bug in the Python tool. Especially since the error hints at this kind of different queries not being supported in the code. Please could you let us know if this is something that can be fixed, either directly in the source code, or alternatively if there is a quick and straight forward patch that we could apply to solve this issue? 

Thank you!

**Comment by JiguangPeng** [comment]
try: demo=AutoPVS1CNV('11-2797090-2869333-DEL', 'hg38')

Please note that CNV module for AutoPVS1 module is not fully evaluated, for reference only.

**Comment by lourdesrosano** [comment]
Hello @JiguangPeng,

This worked beautifully! Thank you so much for your fast answer!

```
>>> from autopvs1 import AutoPVS1CNV
>>> demo=AutoPVS1CNV('11-2797090-2869333-DEL', 'hg38')
>>> print(demo.cnvvariant, demo.transcript.full_name, demo.pvs1.strength.name)
11-2797090-2869333-DEL NM_181798.1 Strong
```
