### ISSUE TITLE
Import python module too slow

### ISSUE THREAD

**Issue by 1seokyoo** [JiguangPeng/autopvs1#16]
The AutoPVS1 program you developed is very good.

I have created and used a script where AutoPVS1 returns PVS1 and strength when variant information is entered.

Whenever the script is executed, the pvs1 module needs to be loaded, but the problem is that the import speed is too slow.

When I checked the pvs1 module, it was confirmed that it took the longest time to construct the transcript data with the pyhgvs module and ncbiRefSeq_hg19.gpe(and hg38).

Building transcript data in _**pvs1.py**_ and _**splicing.py**_ is taking double the time.

The performance is very good, but it would be nice if the speed improved.

please check.

**Comment by JiguangPeng** [comment]
yes, the data load process is slow, there is two way to solve this:
1. for batch use, you only need to import the data once.
2. for frequently discontinuous use, you can create a service to run AutoPSV1 background, and call it when you need it.

**Comment by 1seokyoo** [comment]
Thank you for the reply.

As you said, the API system was developed by using the background to solve the speed problem.
