### ISSUE TITLE
data/hg19.fa missing

### ISSUE THREAD

**Issue by Echopei** [JiguangPeng/autopvs1#6]
there is no file
data/hg19.fa

**Comment by JiguangPeng** [comment]
The hg19 reference file is too big.
You can download it from UCSC Genome Browser

**Comment by Echopei** [comment]
I have this file ,but
![image](https://user-images.githubusercontent.com/10030002/84248122-920d8080-ab3b-11ea-9928-576ac1a1553d.png)

**Comment by JiguangPeng** [comment]
make sure your chromosome name  in the fasta file have 'chr' prefix
